language: RUBY
sudo: false

script:
 - sleep 3
 
notifications:
  webhooks:
    - http://mockbin.org/bin/c5724ab6-e3dc-4b35-b839-b9b3bf2b21df
 
# notifications:
#  email:
#   recipients:
#    - carladrago@gmail.com
#   on_success: always
 
 
##################
