language: RUBY
sudo: false

env:
  - JOB=1
  - JOB=2
  - JOB=3
  - JOB=4
  - JOB=5
  - JOB=6
  - JOB=7
  - JOB=8
  - JOB=9
  - JOB=10
  - JOB=11
  - JOB=12
  - JOB=13
  - JOB=14
  - JOB=15
  - JOB=16
  - JOB=17
  - JOB=18
  - JOB=19
  - JOB=20
  - JOB=21
  - JOB=21
  - JOB=23
  - JOB=24
  - JOB=25
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1
  - JOB=1

script:
 - sleep 3

##################
