language: RUBY
sudo: false

script:
 - sleep 3
 
notifications:
  webhooks:
    - http://mockbin.org/bin/94cb6ebe-7456-4749-a2e8-abe3c146beb3
 
# notifications:
#  email:
#   recipients:
#    - carladrago@gmail.com
#   on_success: always
 
 
##################
