language: node_js
before_install:
  - nvm install 6.2.1
  - node --version
install:
  - npm install
  - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
jobs:
  include:
    - stage: test
      script:
        - echo "Running tests"
    - stage: build
      language: objective-c
      osx_image: xcode8.3
      cache: &cache_macos
        directories:
          - node_modules
          - "$(npm config get prefix)/bin"
          - "$(npm config get prefix)/lib/node_modules"
          - vendor
          - $HOME/Library/Caches/Homebrew
      env:
        - TARGET=ios
        - TARGET_ENV=staging
      after_install: &after_install_macos
        - brew install imagemagick getsentry/tools/sentry-cli
        - bundle install --path vendor/bundle --without development
      script: echo "Building $TARGET for $TARGET_ENV env"
    - language: objective-c
      osx_image: xcode8.3
      cache:
        <<: *cache_macos
      env:
        - TARGET=ios
        - TARGET_ENV=production
      after_install:
        <<: *after_install_macos
      script: echo "Building $TARGET for $TARGET_ENV env"
    - language: android
      components: &components_android
        - build-tools-22.0.1
        - android-22
        - extra-android-m2repository
        - extra-google-google_play_services
        - extra-google-m2repository
        - addon-google_apis-google-19
      env:
        - TARGET=android
        - TARGET_ENV=staging
      cache: &cache_android
        directories:
          - node_modules
          - "$(npm config get prefix)/bin"
          - "$(npm config get prefix)/lib/node_modules"
          - vendor
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      script: echo "Building $TARGET for $TARGET_ENV env"
    - language: android
      components:
        <<: *components_android
      cache:
        <<: *cache_android
      env:
        - TARGET=android
        - TARGET_ENV=production
      script: echo "Building $TARGET for $TARGET_ENV env"
stages:
  - test
  - build
notifications:
  email: false
