language: RUBY

rvm:
  - 1.9.3
  - 2.0.0
  - 2.2

matrix:
  - sudo: required
    dist: trusty
  - sudo: required
    dist: precise
  - sudo: false
    dist: trusty
  - sudo: false
    dist: precise


script:
 - sleep 3
 

# notifications:
#  email:
#   recipients:
#    - carladrago@gmail.com
#   on_success: always
 
 
##################
