jobs:
  include:
    - script: false
      dist: trusty
      rvm: 2.3
      stage: one
    - script: true
      dist: trusty
      rvm: 2.4
      stage: one
    - script: true
      dist: trusty
      stage: two
  allow_failures:
    - rvm: 2.3
